---
title: "Projects and Awards"
---

# Awards

| Date | Award                                                                                                                              |
| ---- | ---------------------------------------------------------------------------------------------------------------------------------- |
| 2023 | Faculty award for excellence in Teaching 2023 (Facultair docent van het jaar 2023)                                                 |
| 2023 | [Best educational product 2023 (Onderwijsproduct van het jaar 2023)](https://gamebrics.nl/nieuws/onderwijsproduct-2023-gamebrics/) |
| 2021 | Open University award for excellence in teaching 2021 (Open Universiteit docent van het jaar 2021)                                 |
| 2020 | Faculty award for excellence in Teaching 2020 (Facultair docent van het jaar 2020)                                                 |
| 2018 | Faculty award for excellence in Teaching 2018 (Facultair docent van het jaar 2018)                                                 |


# Projects

As a researcher and academic, I am actively involved in several exciting projects aimed at enhancing education and learning through innovative technologies and methodologies. Whether it's through the development of serious games, digital assessments, or simulations, each of my projects brings a unique perspective to the field of education. I am proud to work together with my colleagues on these project, and I am eager to share their progress with the world. In this section, you will find a brief overview of each of my current projects, including the funding source and my role on the project.


| Project Name                                                                                                       | Funding Source                                       | Role                   | Description                                                                                                                                                       |
|--------------------------------------------------------------------------------------------------------------------|------------------------------------------------------|------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Serious Game - Junior Scientist                                                                                    | Kwaliteitsafspraken Open University                  | Principal Investigator | A serious game aimed at giving students a consultancy/research-assistant role in a research project to enhance their understanding of methodology and statistics. |
| Chatting with the Past                                                                                             | Leiden Education Innovation                          | Co-Investigator        | A chatbot simulation project to help students see history from the perspective of someone living in the past.                                                     |
| Innovating digital assessment: Effective use of multimedia                                                         | Open University: Call for Interdisciplinary Research | Copromotor             | A project to develop recommendations for the effective use of multimedia in assessments.                                                                          |
| Gamebrics: Serious gaming voor actief online leren met geïntegreerde analytical rubrics voor formatieve e-toetsing | SURF: Activiteitenplan Pijler Online onderwijs       | Co-Investigator        | A project to develop a general rubric for assessing academic skills and communication growth in serious games.                                                    |
| Designer wizard for Serious Games for computational thinking in higher education                                   | Open University: Call for Interdisciplinary Research | Copromotor             | A project to develop a design wizard for serious games as an instructional design aid for teachers in higher education.                                           |